name: bike_client_dealer
description: "A new Flutter project."

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=3.4.1 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  firebase_core: ^2.24.2
  flutter_bloc: ^8.1.6
  flutter_dotenv: ^5.1.0
  get_it: ^7.7.0
  go_router: ^14.2.7
  flutter_secure_storage: ^9.2.2
  flutter_localization: ^0.2.1
  cloud_firestore: ^4.14.0
  firebase_app_check: ^0.2.1+8

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^3.0.0
  build_runner: ^2.4.11
  change_app_package_name: ^1.3.0

flutter:
  generate: true
  uses-material-design: true

  assets:
    - assets/fonts/
  fonts:
    - family: Switzer
      fonts:
        - asset: assets/fonts/Switzer-Thin.otf
          weight: 100
          style: normal
        - asset: assets/fonts/Switzer-Extralight.otf
          weight: 200
          style: normal
        - asset: assets/fonts/Switzer-Light.otf
          weight: 300
          style: normal
        - asset: assets/fonts/Switzer-Regular.otf
          weight: 400
          style: normal
        - asset: assets/fonts/Switzer-Medium.otf
          weight: 500
          style: normal
        - asset: assets/fonts/Switzer-SemiBold.otf
          weight: 600
          style: normal
        - asset: assets/fonts/Switzer-Bold.otf
          weight: 700
          style: normal
        - asset: assets/fonts/Switzer-Black.otf
          weight: 800
          style: normal
        - asset: assets/fonts/Switzer-Extrabold.otf
          weight: 900
          style: normal

