name: bike_client_dealer
description: "A new Flutter project."

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=3.4.1 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  firebase_core: ^2.24.2
  flutter_bloc: ^8.1.6
  flutter_dotenv: ^5.1.0
  get_it: ^7.7.0
  go_router: ^14.2.7
  flutter_secure_storage: ^9.2.2
  cloud_firestore: ^4.14.0
  firebase_app_check: ^0.2.1+8
  firebase_storage: ^11.6.0
  figma_squircle: ^0.5.3
  flutter_svg: ^2.0.10+1
  file_picker: ^8.1.2
  url_launcher: ^6.3.0
  open_file: ^3.5.3
  intl: ^0.19.0
  google_sign_in: ^6.2.1
  firebase_auth: ^4.16.0
  cached_network_image: ^3.4.1
  skeletonizer: ^1.4.2
  lottie: ^3.1.2

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^3.0.0
  build_runner: ^2.4.11
  change_app_package_name: ^1.3.0

flutter:
  # generate: true
  uses-material-design: true

  assets:
    - assets/fonts/
    - assets/icons/
    - assets/company/
    - assets/icons/chats/
    - assets/icons/png/
    - assets/icons/productdetail/
  fonts:
    - family: Inter
      fonts:
        - asset: assets/fonts/Inter_Thin.ttf
          weight: 100
        - asset: assets/fonts/Inter_ExtraLight.ttf
          weight: 200
        - asset: assets/fonts/Inter_Light.ttf
          weight: 300                    
        - asset: assets/fonts/Inter_Regular.ttf
          weight: 400                    
        - asset: assets/fonts/Inter_Medium.ttf
          weight: 500                    
        - asset: assets/fonts/Inter_SemiBold.ttf
          weight: 600                    
        - asset: assets/fonts/Inter_Bold.ttf
          weight: 700                    
        - asset: assets/fonts/Inter_ExtraBold.ttf
          weight: 800                    
        - asset: assets/fonts/Inter_Black.ttf
          weight: 900                    
